x = 20
y = 3
print("RESULTADO:",x + y) # (+)SUMA LAS 2 VARIABLES

print("RESULTADO:",x - y) # (-)RESTA LAS 2 VARIABLES

print("RESULTADO:",x * y) # (*)MULTIPLICA LAS 2 VARIABLES 

print("RESULTADO:",x / y) # (/)DIVIDE LAS 2  VARIABLES

print("RESULTADO:",x // y) # (//)DIVIDE LAS 2 VARIABLES COMO RESULTADO ENTERO, SI EL RESULTADO ES MAYOR ,50 SE VA A REDONDEAR PARA ABAJO

print("RESULTADO:",x % y) # (%)DA EL RESTO DE UNA DIVISIÓN ENTERA ENTRE LAS 2 VARIABLES

print("RESULTADO:",x ** y) # (**)CALCULA LA POTENCIA ENTRE LAS DOS VARIABLES 
